//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHOPPER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienTheSanPham
    {
        public string MaBienThe { get; set; }
        public string MaSP { get; set; }
        public string MaMau { get; set; }
        public string MaSize { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
        public int SoLuongTon { get; set; }
        public string AnhBienThe { get; set; }
    
        public virtual MauSac MauSac { get; set; }
        public virtual KichThuoc KichThuoc { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
