//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHOPPER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_DChiKhachHang
    {
        public string MaDC { get; set; }
        public int MaKH { get; set; }
        public string DiaChiCuThe { get; set; }
    
        public virtual DiaChiKhachHang DiaChiKhachHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
