//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHOPPER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctiet_PhieuGiamGia
    {
        public string MaGG { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SLuongPhieu { get; set; }
    
        public virtual PhieuGiamGia PhieuGiamGia { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
