//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHOPPER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucSanPham()
        {
            this.DanhMucSanPham1 = new HashSet<DanhMucSanPham>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaDM { get; set; }
        public string TenDanhMuc { get; set; }
        public Nullable<int> MaDanhMucCha { get; set; }
        public Nullable<int> SoLuongSanPham { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMucSanPham> DanhMucSanPham1 { get; set; }
        public virtual DanhMucSanPham DanhMucSanPham2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
