//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHOPPER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChiKhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiaChiKhachHang()
        {
            this.ChiTiet_DChiKhachHang = new HashSet<ChiTiet_DChiKhachHang>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MaDC { get; set; }
        public int MaKH { get; set; }
        public string SoNha { get; set; }
        public string Duong { get; set; }
        public string TinhThanh { get; set; }
        public string QuanHuyen { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_DChiKhachHang> ChiTiet_DChiKhachHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
