//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHOPPER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string MaKM { get; set; }
        public string MaSP { get; set; }
        public string TenChuongTrinh { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> PhanTramGiam { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string TrangThaiKM { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
