//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESHOPPER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuGiamGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuGiamGia()
        {
            this.Ctiet_PhieuGiamGia = new HashSet<Ctiet_PhieuGiamGia>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MaGG { get; set; }
        public string TenMa { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaTriGiam { get; set; }
        public Nullable<bool> PhanTram { get; set; }
        public Nullable<int> SoLanSuDung { get; set; }
        public Nullable<System.DateTime> NgayBDau { get; set; }
        public Nullable<System.DateTime> NgayKthuc { get; set; }
        public string TrangThaiGG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctiet_PhieuGiamGia> Ctiet_PhieuGiamGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
